baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 10
disqusShortname = "agentbaxx"

[params]
contentTypeName = "post"
themeColor = "green"
showMenuItems = 4
fullWidthTheme = false
centerTheme = true


[languages]
[languages.en]
title = "mcbunkus"
subtitle = "general menace to society"
keywords = ""
copyright = "&copy; 2024 mcbunkus industries"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "mcbunkus"
logoHomeLink = "/"

[languages.en.menu]

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 1

[[languages.en.menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume"
weight = 2
