baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 10
disqusShortname = "agentbaxx"

[params]
contentTypeName = "post"
themeColor = "green"
showMenuItems = 4
fullWidthTheme = false
centerTheme = true


[languages]
[languages.en]
title = "Austen LeBeau"
subtitle = ""
keywords = ""
copyright = "&copy; 2023 Austen LeBeau"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "Austen LeBeau"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 1
[[languages.en.menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume"
weight = 2
[[languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 3
